# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "свекла",
  "description": "Лучшая свекла на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=свекла
Content-Type: application/json

###

# создание склада
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "Сахарова 1",
  "positions": [
    {
      "product": 2,
      "quantity": 50,
      "price": 110
    },
    {
      "product": 3,
      "quantity": 90,
      "price": 170
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/2/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    },
    {
      "product": 4,
      "quantity": 43,
      "price": 45
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=4
Content-Type: application/json

###

DELETE {{baseUrl}}/stocks/1/
Content-Type: application/json



